language: node_js
node_js:
  - "8"
before_install:
  - "npm install -g npm@latest"
  - "npm install -g eslint"
  - "npm install -g eslint-config-aqua"
install:
  - "npm i"
cache:
  directories:
    - "node_modules"